import socket
import csv

# Read CSV file generated by the previous code
def read_csv(filename):
    data = []
    with open(filename, 'r') as file:
        reader = csv.DictReader(file)
        for row in reader:
            data.append(row)
    return data

# Check if coordinates are present in the CSV file
def check_coordinates(latitude, longitude, data):
    for row in data:
        if float(row['average_latitude']) == latitude and float(row['average_longitude']) == longitude:
            return True
    return False

# Server configuration
HOST = '127.0.0.1'
PORT = 65432

# Read the CSV file
csv_data = read_csv('output.csv')
print(csv_data)

# Create a socket
with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as server_socket:
    server_socket.bind((HOST, PORT))
    server_socket.listen()
    print("Server on")
    conn, addr = server_socket.accept()
    with conn:
        print('Connected by', addr)
        while True:
            # Receive coordinates from the client
            data = conn.recv(1024).decode()
            if not data:
                break
            print('Received coordinates:', data)
            # Parse coordinates
            latitude, longitude = map(float, data.split(','))
            # Check if coordinates are present in the CSV file
            if check_coordinates(latitude, longitude, csv_data):
                conn.sendall(b'Coordinates present in CSV file')
            else:
                conn.sendall(b'Coordinates not found in CSV file')
